# Generated by Django 3.1.7 on 2021-04-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_userdevice_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='token_not_registered',
            field=models.BooleanField(default=False),
        ),
    ]
