# Generated by Django 3.1.7 on 2021-04-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_userdevice_token_not_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=100)),
                ('notification_body', models.CharField(max_length=1000)),
            ],
        ),
    ]
